FROM golang:1.17

WORKDIR /go/src/github.com/replicatedhq/kurl/

## Get deps
ADD go.mod go.sum $PROJECT_PATH
RUN --mount=target=/root/.cache,type=cache go mod download

WORKDIR /go/src/github.com/replicatedhq/kurl/testgrid/tgapi/

## Now add the project and compile
COPY testgrid/tgapi .
RUN --mount=target=/root/.cache,type=cache make build

EXPOSE 3000
EXPOSE 6060

RUN mv ./bin/tgapi /tgapi
