FROM postgres:10.7

ENV POSTGRES_USER=testgrid
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=testgrid

ADD . /go/src/github.com/replicatedhq/kurl/testgrid/migrations
WORKDIR /go/src/github.com/replicatedhq/kurl/testgrid/migrations
