# Source: rook-ceph/templates/configmap.yaml
# ImageSet ConfigMap defines the container images used by the CSI drivers.
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-csi-operator-image-set-configmap
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: replaceme
    app.kubernetes.io/version: v1.20.7
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.20.7"
data:
  provisioner: "registry.k8s.io/sig-storage/csi-provisioner:v6.2.0"
  attacher: "registry.k8s.io/sig-storage/csi-attacher:v4.12.0"
  resizer: "registry.k8s.io/sig-storage/csi-resizer:v2.1.0"
  snapshotter: "registry.k8s.io/sig-storage/csi-snapshotter:v8.5.0"
  registrar: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.17.0"
  plugin: "quay.io/cephcsi/cephcsi:v3.17.1"
  addons: "quay.io/csiaddons/k8s-sidecar:v0.14.0"
---
---
# Source: rook-ceph/templates/configmap.yaml
# Operator settings that can be updated without an operator restart
# Operator settings that require an operator restart are found in the operator env vars
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: replaceme
    app.kubernetes.io/version: v1.20.7
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.20.7"
data:
  ROOK_LOG_LEVEL: "INFO"
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
  ROOK_OBC_ALLOW_ADDITIONAL_CONFIG_FIELDS: "maxObjects,maxSize"
  ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
  ROOK_CEPH_MON_RUN_AS_ROOT: "false"
  ROOK_DELETE_UNUSED_CRUSH_RULES: "true"
  ROOK_ENABLE_DISCOVERY_DAEMON: "true"
---
