apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
metadata:
  name: kubeadm-join-configuration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
  - name: container-runtime-endpoint
    value: unix:///run/containerd/containerd.sock
