FROM node:8-slim

ARG version=unknown
ENV VERSION=$version

ADD web /src
ADD dist /dist
ADD build/templates /templates

WORKDIR /src

RUN chmod +x /src/bin/kurl

EXPOSE 3000
CMD ["node", "--no-deprecation", "bin/kurl", "serve"]
