FROM node:12-slim

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq \
  && apt-get install --no-install-recommends -y ca-certificates \
  && update-ca-certificates

ARG version=unknown
ENV VERSION=$version

ARG version_tag="latest"
ENV KURL_BIN_UTILS_FILE=kurl-bin-utils-${version_tag}.tar.gz

ARG KURL_UTIL_IMAGE
ENV KURL_UTIL_IMAGE=$KURL_UTIL_IMAGE

ADD web /src
ADD build/templates /templates
ADD build/bin/server /bin

WORKDIR /src

RUN chmod +x /src/bin/kurl

EXPOSE 3000
CMD ["node", "--no-deprecation", "bin/kurl", "serve"]
