
CONTOUR_VERSION="latest"

#docker flags
DOCKER_VERSION="latest"
ADDITIONAL_NO_PROXY="1.1.1.1"
BYPASS_STORAGEDRIVER_WARNING=1
DOCKER_REGISTRY_IP="1.1.1.1"
HARD_FAIL_ON_LOOPBACK=1
NO_CE_ON_EE=1
SKIP_DOCKER_INSTA=1

#fluentd flags
FLUENTD_FULL_EFK_STACK=1
FLUENTD_VERSION="latest"

#kotsadm flags
KOTSADM_APPLICATION_NAMESPACE="1.1.1.1"
KOTSADM_APPLICATION_SLUG="slug"
KOTSADM_HOSTAME="1.1.1.1"
KOTSADM_UI_BIND_PORT=24
KOTSADM_VERSION="latest"

#kubernetes flags
API_SERVICE_ADDRESS="1.1.1.1"
BOOTSTRAP_TOKEN="secret"
BOOTSTRAP_TOKEN_TTL="forever"
CERT_KEY="here"
MASTER=1
KUBEADM_TOKEN_CA_HASH="ceaser"
LOAD_BALANCER_ADDRESS="localhost"
HA_CLUSTER=1
KUBERNETES_MASTER_ADDR="1.1.1.1"
SERVICE_CIDR="1.2.2.2"
SERVICE_CIDR_RANGE="/24"
KUBERNETES_VERSION="latest"

#kurl flags
PROXY_ADDRESS="1.1.1.1"
AIRGAP=
BYPASS_FIREWALLD_WARNING=1
HARD_FAIL_ON_FIREWALLD=
HOSTNAME_CHECK="here"
NO_PROXY=1
PRIVATE_ADDRESS="SECRET"
PUBLIC_ADDRESS="NOT_SECRET"
TASK="important"

#minio flags
MINIO_NAMEPSACE="minio"
MINIO_VERSION="latest"

#openebs flags
OPENEBS_NAMESPACE="open"
OPENEBS_LOCALPV="1"
OPENEBS_LOCALPV_STORAGE_CLASS="default"
OPENEBS_CSTOR="1"
OPENEBS_CSTOR_STORAGE_CLASS="cstor"

OPENEBS_VERSION="latest"

#prometheus flags
PROMETHEUS_VERSION="latest"

#registry flags
REGISTRY_PUBLISH_PORT=23
REGISTRY_VERSION="latest"

#rook flags
STORAGE_CLASS="sk"
CEPH_POOL_REPLICAS=24
ROOK_VERSION="latest"

#velero yaml
VELERO_USE_RESTIC=1
VELERO_INSTALL_CLI=1
VELERO_LOCAL_BUCKET="here"
VELERO_NAMESPACE="velero"
VELERO_VERSION="latest"

#weave yaml
ENCRYPT_NETWORK=1
WEAVE_POD_CIDR="1.1.1.1"
WEAVE_POD_CIDR_RANGE="/24"
WEAVE_VERSION="latest"

apply_flags_to_installer_yaml "$1"
