DOCKER_VERSION=poop
NO_PROXY=1
KUBERNETES_VERSION="latest"
WEAVE_VERSION="latest"
MINIO_VERSION="latest"
OPENEBS_VERSION="latest"
PROMETHEUS_VERSION="latest"
FLUENTD_VERSION="latest"
ROOK_VERSION="latest"
REGISTRY_VERSION="latest"
VELERO_VERSION="latest"
CONTOUR_VERSION="latest"
KOTSADM_VERSION="latest"

apply_flags_to_yaml "$1"
