---
apiVersion: kubeadm.k8s.io/$(kubeadm_conf_api_version)
kind: ClusterConfiguration
metadata:
  name: kubeadm-cluster-configuration
kubernetesVersion: v$KUBERNETES_VERSION
certificatesDir: /etc/kubernetes/pki
clusterName: $KUBERNETES_CLUSTER_NAME
controllerManager:
  extraArgs:
  - name: profiling
    value: '"false"'
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
    - name: cipher-suites
      value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
networking:
  serviceSubnet: $SERVICE_CIDR
apiServer:
  extraArgs:
  - name: service-node-port-range
    value: "80-60000"
  - name: tls-cipher-suites
    value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - name: profiling
    value: '"false"'
  - name: audit-log-path
    value: /auditlog/k8s-audit.log
  - name: audit-policy-file
    value: /etc/kubernetes/audit.yaml
  - name: audit-log-maxage
    value: '"30"'
  - name: audit-log-maxsize
    value: '"100"'
  - name: audit-log-maxbackup
    value: '"10"'
  extraVolumes:
    - name: audit
      hostPath: /etc/kubernetes/audit.yaml
      mountPath: /etc/kubernetes/audit.yaml
      readOnly: true
      pathType: File
    - name: auditlog
      hostPath: /var/log/apiserver
      mountPath: /auditlog
      pathType: Directory
  certSANs:
  - "$PRIVATE_ADDRESS"
scheduler:
  extraArgs:
  - name: profiling
    value: '"false"'
