name: cron-scan-images-daily

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  build-matrix:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - name: Install dependencies
        working-directory: ./bin/scan-images/
        run: npm install
      - id: set-matrix
        name: Build image matrix
        run: |
          echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
          ./bin/scan-images/matrix.js >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  scan-images:
    name: ${{ matrix.addon }}:${{ matrix.version }} - ${{ matrix.name }}
    needs: build-matrix
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
      fail-fast: false
      max-parallel: 5
    steps:
      - name: Checkout for Grype config
        uses: actions/checkout@v6
        with:
          sparse-checkout: .grype.yaml
          sparse-checkout-cone-mode: false

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: "Scan image (OS vulnerabilities only)"
        id: scan
        continue-on-error: ${{ ! matrix.maintainer }}
        run: |
          syft ${{ matrix.image }} -o syft-json --select-catalogers "os" > sbom.json
          grype sbom:./sbom.json -c .grype.yaml --fail-on high --only-fixed -o json > grype.json

      - name: "Upload artifact"
        uses: actions/upload-artifact@v7
        if: ${{ always() && steps.scan.outcome == 'failure' }}
        with:
          name: ${{ matrix.addon }}-${{ matrix.version }}-${{ matrix.name }}
          path: grype.json

      - name: "Display results"
        if: ${{ always() && steps.scan.outcome == 'failure' }}
        continue-on-error: ${{ ! matrix.maintainer }}
        run: grype sbom:./sbom.json -c .grype.yaml --fail-on high --only-fixed -o table

  collect-results:
    needs: scan-images
    runs-on: ubuntu-24.04
    if: ${{ failure() }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: scan-results/
      - name: Collect results
        run: |
          jq -s '.' scan-results/*/grype.json > grype.json
      - name: "Upload artifact"
        uses: actions/upload-artifact@v7
        with:
          name: grype results
          path: grype.json
