FROM repldev/kurl:latest

WORKDIR /src

ADD Makefile .
ADD package.json .
ADD yarn.lock .
RUN make deps

ADD . .
RUN make build

EXPOSE 3000

ENTRYPOINT ["node", "--no-deprecation", "bin/kurl", "serve"]
